
- name: Install a list of packages
  apt:
    pkg:
      - build-essential 
      - cmake
      - pkg-config
      - yasm
      - git
      - checkinstall
      - libjpeg-dev 
      - libpng-dev 
      - libtiff-dev
      - libavcodec-dev
      - libavformat-dev 
      - libswscale-dev 
      - libavresample-dev 
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libxvidcore-dev 
      - x264 
      - libx264-dev 
      - libfaac-dev 
      - libmp3lame-dev 
      - libtheora-dev
      - libfaac-dev 
      - libmp3lame-dev 
      - libvorbis-dev
      - libopencore-amrnb-dev 
      - libdc1394-22 
      - libdc1394-22-dev
      - libxine2-dev 
      - libv4l-dev 
      - v4l-utils  


# # sudo ln -s -f ../libv4l1-videodev.h videodev.h 

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/include/libv4l1-videodev.h
    dest: /usr/include/linux/videodev.h 
    state: link

- name: Install opencv dependencies
  apt:
    pkg:
      - libgtk-3-dev
      - python3-dev 
      - python3-pip 
      - python3-testresources
      - libtbb-dev
      - libatlas-base-dev
      - gfortran
      - libprotobuf-dev
      - protobuf-compiler
      - libgoogle-glog-dev
      - libgflags-dev
      - libgphoto2-dev
      - libeigen3-dev
      - libhdf5-dev
      - doxygen

- name: Install opencv Python 3 packages
  pip:
    name: 
      - dlib
      - tensorflow
      - scipy
      - matplotlib
      - scikit-image
      - scikit-learn
    executable: pip3

# - name: Clone opencv repo
#   ansible.builtin.git:
#     repo: https://github.com/opencv/opencv.git
#     dest: /

# - name: Clone opencv-contrib repo
#   ansible.builtin.git:
#     repo: https://github.com/opencv/opencv_contrib.git
#     dest: /

- name: Git checkout
  ansible.builtin.git:
    repo: https://github.com/opencv/opencv.git
    dest: ~/opencv
    version: 4.5.1


- name: Git checkout
  ansible.builtin.git:
    repo: https://github.com/opencv/opencv_contrib.git
    dest: ~/opencv_contrib
    version: 4.5.1
